C:\Users\Ji\AppData\Local\Programs\Python\Python39\python.exe "C:/Program Files/JetBrains/PyCharm 2022.2.2/plugins/python/helpers/pycharm/_jb_unittest_runner.py" --target minegenerator_test.MinegeneratorTest.test_gen_random_minefield 
Testing started at 4:23 PM ...
Launching unittests with arguments python -m unittest minegenerator_test.MinegeneratorTest.test_gen_random_minefield in C:\Users\Ji\PycharmProjects\504pythonProject\TCSS504_MineSweeper









































































































Ran 1 test in 0.028s

OK

Process finished with exit code 0